export const TARGETING_HOSTS = 'TARGETING_HOSTS';
export const ADD_SELECTED_TARGETING_HOST = 'ADD_SELECTED_TARGETING_HOST';
export const REMOVE_SELECTED_TARGETING_HOST = 'REMOVE_SELECTED_TARGETING_HOST';
export const SELECT_ALL_TARGETING_HOSTS = 'SELECT_ALL_TARGETING_HOSTS';
